Lmod has detected the following error: The following module(s) are unknown:
"anaconda3"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "anaconda3"

Also make sure that all modulefiles written in TCL start with the string
#%Module



wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: soda4fries (soda4fries-university-of-malaya). Use `wandb login --relogin` to force relogin
wandb: ERROR failed to upsert bucket: api: failed sending: POST https://api.wandb.ai/graphql giving up after 1 attempt(s): Post "https://api.wandb.ai/graphql": tls: failed to verify certificate: x509: certificate signed by unknown authority
Traceback (most recent call last):
  File "/scr/user/mahdinur/CVPR/2022-CVPR-AirNet/train.py", line 20, in <module>
    wandb.init(project='WaveletTrain', name="Test1", config={
  File "/home/user/mahdinur/.conda/envs/CFP/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1248, in init
    wandb._sentry.reraise(e)
  File "/home/user/mahdinur/.conda/envs/CFP/lib/python3.12/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/user/mahdinur/.conda/envs/CFP/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1234, in init
    return wi.init()
           ^^^^^^^^^
  File "/home/user/mahdinur/.conda/envs/CFP/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 831, in init
    raise error
wandb.errors.CommError: failed to upsert bucket: api: failed sending: POST https://api.wandb.ai/graphql giving up after 1 attempt(s): Post "https://api.wandb.ai/graphql": tls: failed to verify certificate: x509: certificate signed by unknown authority
